version: '3'

services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/code:ro
    environment:
      - DATABASE_URL=postgresql://postgres:Bright#1270@localhost:5433/dockert
    ports:
      - "8000:80"

  db:
      image: postgres:15-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      expose:
        - 5433
      environment:
        - POSTGRES_USER=fastapi_user
        - POSTGRES_PASSWORD=fastapi_pass
        - POSTGRES_DB=user_management

volumes:
      postgres_data: 